FROM cypress/base:20.17.0

# Install jq for escaping strings
RUN apt-get update && \
    apt-get install -y jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /correction

COPY package*.json ./
RUN yarn install && \
    rm -rf /usr/local/share/.cache/yarn

COPY . .

# Command to run the tests
CMD ["/correction/run_tests.sh"]
