FROM cypress/base:20.17.0

WORKDIR /correction

COPY package*.json ./
RUN yarn install && \
    rm -rf /usr/local/share/.cache/yarn

COPY . .

# Command to run the tests
CMD ["/correction/run_tests.sh"]
